/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-surface-variant": "#45474e",
        "inverse-primary": "#b7c6ed",
        "outline-variant": "#c5c6ce",
        "surface-dim": "#d8d7fb",
        "on-background": "#181934",
        "on-surface": "#181934",
        "surface-container": "#efecff",
        "secondary": "#006b55",
        "inverse-surface": "#2d2e4a",
        "tertiary-container": "#2f1c00",
        "surface-bright": "#fcf8ff",
        "on-error": "#ffffff",
        "secondary-fixed-dim": "#3adeb5",
        "surface-tint": "#505e80",
        "surface-container-lowest": "#ffffff",
        "error": "#ba1a1a",
        "on-primary-fixed-variant": "#384667",
        "outline": "#75777e",
        "on-tertiary": "#ffffff",
        "surface-container-highest": "#e2dfff",
        "primary": "#00071b",
        "on-tertiary-container": "#ba7a00",
        "surface": "#fcf8ff",
        "tertiary-fixed-dim": "#ffb955",
        "surface-variant": "#e2dfff",
        "primary-container": "#0f1f3d",
        "tertiary": "#0f0600",
        "primary-fixed": "#d8e2ff",
        "primary-fixed-dim": "#b7c6ed",
        "on-error-container": "#93000a",
        "secondary-fixed": "#60fbd0",
        "surface-container-low": "#f5f2ff",
        "on-secondary": "#ffffff",
        "on-primary": "#ffffff",
        "error-container": "#ffdad6",
        "on-primary-container": "#7887ab",
        "on-primary-fixed": "#0a1b39",
        "tertiary-fixed": "#ffddb4",
        "secondary-container": "#5df8ce",
        "on-tertiary-fixed-variant": "#633f00",
        "on-secondary-fixed": "#002118",
        "on-secondary-fixed-variant": "#00513f",
        "on-tertiary-fixed": "#291800",
        "on-secondary-container": "#007059",
        "inverse-on-surface": "#f2efff",
        "surface-container-high": "#e8e6ff",
        "background": "#fcf8ff"
      }
    },
  },
  plugins: [],
}
