-- AI-Powered Career Skills Development Platform
-- PostgreSQL Database Schema

-- Users table
CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    full_name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Onboarding profiles
CREATE TABLE user_profiles (
    id SERIAL PRIMARY KEY,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    sector_type VARCHAR(50) NOT NULL CHECK (sector_type IN ('Private', 'Government')),
    organization_name VARCHAR(255) NOT NULL,
    department_id INTEGER REFERENCES departments(id),
    custom_department VARCHAR(255), -- if not in pre-loaded list
    job_title VARCHAR(255) NOT NULL,
    years_experience INTEGER NOT NULL,
    current_tools TEXT[], -- array of tools currently used
    onboarding_completed BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(user_id)
);

-- Pre-loaded departments (especially for government)
CREATE TABLE departments (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    sector_type VARCHAR(50) NOT NULL CHECK (sector_type IN ('Private', 'Government', 'Both')),
    standard_functions TEXT[], -- pre-seeded context for AI
    description TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Job tasks generated by AI
CREATE TABLE job_tasks (
    id SERIAL PRIMARY KEY,
    user_profile_id INTEGER REFERENCES user_profiles(id) ON DELETE CASCADE,
    category VARCHAR(100) NOT NULL, -- data, communication, reporting, admin, etc.
    task_name VARCHAR(500) NOT NULL,
    task_description TEXT,
    frequency VARCHAR(50), -- daily, weekly, monthly
    complexity VARCHAR(50), -- low, medium, high
    is_approved BOOLEAN DEFAULT FALSE,
    is_custom BOOLEAN DEFAULT FALSE, -- user-added task
    display_order INTEGER,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Skill taxonomy (pre-seeded mappings)
CREATE TABLE skill_taxonomy (
    id SERIAL PRIMARY KEY,
    skill_name VARCHAR(255) NOT NULL,
    skill_category VARCHAR(100), -- technical, communication, analytical, etc.
    related_tasks TEXT[], -- common task keywords this skill addresses
    difficulty_level VARCHAR(50), -- beginner, intermediate, advanced
    description TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- AI tools database
CREATE TABLE ai_tools (
    id SERIAL PRIMARY KEY,
    tool_name VARCHAR(255) NOT NULL UNIQUE,
    tool_category VARCHAR(100), -- productivity, design, data, writing, etc.
    description TEXT,
    official_url VARCHAR(500),
    difficulty_level VARCHAR(50),
    is_free BOOLEAN DEFAULT FALSE,
    pricing_info TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Skill gaps identified for user
CREATE TABLE user_skill_gaps (
    id SERIAL PRIMARY KEY,
    user_profile_id INTEGER REFERENCES user_profiles(id) ON DELETE CASCADE,
    job_task_id INTEGER REFERENCES job_tasks(id) ON DELETE CASCADE,
    skill_id INTEGER REFERENCES skill_taxonomy(id),
    tool_id INTEGER REFERENCES ai_tools(id),
    gap_description TEXT,
    priority INTEGER, -- 1-5, higher is more important
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Learning courses (generated per user)
CREATE TABLE courses (
    id SERIAL PRIMARY KEY,
    user_profile_id INTEGER REFERENCES user_profiles(id) ON DELETE CASCADE,
    course_title VARCHAR(255) NOT NULL,
    course_description TEXT,
    total_modules INTEGER DEFAULT 0,
    estimated_hours DECIMAL(5,2),
    is_completed BOOLEAN DEFAULT FALSE,
    completion_date TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Course modules
CREATE TABLE course_modules (
    id SERIAL PRIMARY KEY,
    course_id INTEGER REFERENCES courses(id) ON DELETE CASCADE,
    tool_id INTEGER REFERENCES ai_tools(id),
    module_title VARCHAR(255) NOT NULL,
    module_order INTEGER NOT NULL,
    estimated_minutes INTEGER,
    is_completed BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Lessons within modules
CREATE TABLE lessons (
    id SERIAL PRIMARY KEY,
    module_id INTEGER REFERENCES course_modules(id) ON DELETE CASCADE,
    lesson_type VARCHAR(50) NOT NULL CHECK (lesson_type IN ('video', 'guide', 'quiz', 'practice')),
    lesson_title VARCHAR(255) NOT NULL,
    lesson_order INTEGER NOT NULL,
    content_data JSONB, -- stores video URLs, guide text, quiz questions, etc.
    is_completed BOOLEAN DEFAULT FALSE,
    completed_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- YouTube videos curated for lessons
CREATE TABLE youtube_videos (
    id SERIAL PRIMARY KEY,
    lesson_id INTEGER REFERENCES lessons(id) ON DELETE CASCADE,
    video_id VARCHAR(50) NOT NULL, -- YouTube video ID
    video_title VARCHAR(500),
    channel_name VARCHAR(255),
    view_count BIGINT,
    rating DECIMAL(3,2),
    duration INTEGER, -- in seconds
    video_order INTEGER,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Quizzes
CREATE TABLE quizzes (
    id SERIAL PRIMARY KEY,
    module_id INTEGER REFERENCES course_modules(id) ON DELETE CASCADE,
    quiz_title VARCHAR(255) NOT NULL,
    passing_score INTEGER DEFAULT 80, -- percentage
    video_id VARCHAR(50), -- track which video the quiz is for
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Quiz questions
CREATE TABLE quiz_questions (
    id SERIAL PRIMARY KEY,
    quiz_id INTEGER REFERENCES quizzes(id) ON DELETE CASCADE,
    question_text TEXT NOT NULL,
    question_type VARCHAR(50) DEFAULT 'multiple_choice',
    options JSONB, -- array of options
    correct_answer TEXT NOT NULL,
    explanation TEXT,
    question_order INTEGER,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- User quiz attempts
CREATE TABLE quiz_attempts (
    id SERIAL PRIMARY KEY,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    quiz_id INTEGER REFERENCES quizzes(id) ON DELETE CASCADE,
    score INTEGER NOT NULL,
    total_questions INTEGER NOT NULL,
    passed BOOLEAN,
    attempt_number INTEGER DEFAULT 1,
    answers_data JSONB, -- stores user's answers
    completed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- User selected tools (for onboarding flow)
CREATE TABLE user_selected_tools (
    id SERIAL PRIMARY KEY,
    user_profile_id INTEGER REFERENCES user_profiles(id) ON DELETE CASCADE,
    tool_id INTEGER REFERENCES ai_tools(id) ON DELETE CASCADE,
    is_custom BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(user_profile_id, tool_id)
);

COMMENT ON TABLE user_selected_tools IS 'Stores user-selected AI tools during onboarding flow';

-- Progress tracking
CREATE TABLE user_progress (
    id SERIAL PRIMARY KEY,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    course_id INTEGER REFERENCES courses(id) ON DELETE CASCADE,
    module_id INTEGER REFERENCES course_modules(id),
    lesson_id INTEGER REFERENCES lessons(id),
    progress_percentage DECIMAL(5,2) DEFAULT 0,
    last_accessed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    time_spent_minutes INTEGER DEFAULT 0,
    UNIQUE(user_id, course_id)
);

-- Daily streaks and engagement
CREATE TABLE user_streaks (
    id SERIAL PRIMARY KEY,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    current_streak INTEGER DEFAULT 0,
    longest_streak INTEGER DEFAULT 0,
    last_activity_date DATE,
    total_learning_days INTEGER DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(user_id)
);

-- AI mentor chat history
CREATE TABLE chat_history (
    id SERIAL PRIMARY KEY,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    message_type VARCHAR(50) CHECK (message_type IN ('user', 'assistant')),
    message_text TEXT NOT NULL,
    context_data JSONB, -- current lesson, module info
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Certificates
CREATE TABLE certificates (
    id SERIAL PRIMARY KEY,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    course_id INTEGER REFERENCES courses(id) ON DELETE CASCADE,
    certificate_number VARCHAR(100) UNIQUE NOT NULL,
    verification_hash VARCHAR(255) UNIQUE NOT NULL, -- SHA-256 hash
    tools_mastered TEXT[],
    issue_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    pdf_url VARCHAR(500),
    is_verified BOOLEAN DEFAULT TRUE
);

-- Indexes for performance
CREATE INDEX idx_user_profiles_user_id ON user_profiles(user_id);
CREATE INDEX idx_job_tasks_user_profile_id ON job_tasks(user_profile_id);
CREATE INDEX idx_courses_user_profile_id ON courses(user_profile_id);
CREATE INDEX idx_lessons_module_id ON lessons(module_id);
CREATE INDEX idx_user_progress_user_id ON user_progress(user_id);
CREATE INDEX idx_certificates_verification_hash ON certificates(verification_hash);
CREATE INDEX idx_departments_sector_type ON departments(sector_type);
CREATE INDEX idx_user_selected_tools_profile ON user_selected_tools(user_profile_id);
CREATE INDEX idx_user_selected_tools_tool ON user_selected_tools(tool_id);
CREATE INDEX idx_quizzes_video_id ON quizzes(video_id);
CREATE INDEX idx_quizzes_module_video ON quizzes(module_id, video_id);

-- Seed government departments
INSERT INTO departments (name, sector_type, standard_functions, description) VALUES
('Federal Investigation Agency (FIA)', 'Government', 
 ARRAY['cybercrime investigation', 'immigration control', 'anti-corruption', 'counter-terrorism', 'border security'],
 'Pakistan''s premier federal law enforcement agency'),
 
('Intelligence Bureau (IB)', 'Government',
 ARRAY['internal intelligence', 'security clearances', 'threat assessment', 'surveillance operations', 'counter-intelligence'],
 'Pakistan''s domestic intelligence agency'),
 
('National Database and Registration Authority (NADRA)', 'Government',
 ARRAY['citizen registration', 'identity verification', 'biometric data management', 'national ID cards', 'database administration'],
 'National database and registration authority'),
 
('Power and Works Department', 'Government',
 ARRAY['infrastructure development', 'power distribution', 'construction management', 'maintenance', 'project oversight'],
 'Responsible for power infrastructure and public works'),
 
('Ministry of Finance', 'Government',
 ARRAY['budget planning', 'financial policy', 'revenue collection', 'economic analysis', 'fiscal reporting'],
 'Federal ministry managing national finances'),
 
('Education Department', 'Government',
 ARRAY['curriculum development', 'teacher training', 'school administration', 'student assessment', 'policy implementation'],
 'Provincial/federal education administration');

-- Seed common private departments
INSERT INTO departments (name, sector_type, standard_functions, description) VALUES
('Human Resources', 'Both',
 ARRAY['recruitment', 'employee onboarding', 'performance management', 'payroll', 'training and development', 'policy creation'],
 'Manages employee lifecycle and organizational culture'),
 
('Marketing', 'Both',
 ARRAY['campaign management', 'social media', 'content creation', 'market research', 'brand management', 'lead generation'],
 'Promotes products/services and builds brand awareness'),
 
('Sales', 'Private',
 ARRAY['client outreach', 'pipeline management', 'proposal creation', 'negotiation', 'CRM management', 'revenue reporting'],
 'Drives revenue through customer acquisition and retention'),
 
('IT/Technology', 'Both',
 ARRAY['software development', 'system maintenance', 'cybersecurity', 'technical support', 'infrastructure management'],
 'Manages technology systems and infrastructure'),
 
('Finance/Accounting', 'Both',
 ARRAY['financial reporting', 'bookkeeping', 'budget management', 'tax compliance', 'audit preparation', 'expense tracking'],
 'Manages financial operations and compliance'),
 
('Operations', 'Both',
 ARRAY['process optimization', 'supply chain', 'quality control', 'inventory management', 'logistics coordination'],
 'Manages day-to-day business operations');
